### ISSUE TITLE
Wont Build

### ISSUE THREAD

**Issue by ksuchar** [ConnorDCrawford/TUrnt#1]
Hi, after downloading the project and trying to run I get the following error:

error: unable to read module map contents from 'Target Support Files/MGSwipeTableCell/MGSwipeTableCell.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “MGSwipeTableCell.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/KyleSuchar/Downloads/TUrnt-master-3/Pods/Target Support Files/MGSwipeTableCell/MGSwipeTableCell.modulemap, NSUnderlyingError=0x7fd7484ab370 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
warning: no umbrella header found for target 'MGSwipeTableCell', module map will not be generated

Any help would be greatly appreciated! Love the app by the way!

**Comment by ConnorDCrawford** [comment]
Hello! Try downloading and building the latest commit. This is a pesky issue caused by a Cocoapods bug that arises when using static libraries. However, I believe I've fixed it.

If this doesn't work, I've also found that using a Cocoapods version <1.0 and running "pod install" again can fix the problem, as well as doing a Clean prior to building the project. Let me know if the latest commit fixes the problem for you.

You're welcome, and thanks!

**Comment by ksuchar** [comment]
Hi, unfortunately it still has the same errors. I am not exactly sure what you mean in the second recommendation you gave.

**Comment by ConnorDCrawford** [comment]
It looks like the issue was actually separate from what I was describing, but I believe I've fixed it in the latest commit. However, the project still will not build because it requires a GoogleService-Info.plist, which I unfortunately cannot provide because it contains private API keys. You can get your own copy of it by setting up [Google Sign-In](https://developers.google.com/identity/sign-in/ios/start?ver=swift) and [Firebase](https://firebase.google.com/docs/ios/setup). Also, you'll need your own Info.plist, which you can obtain from by creating a new Xcode project and copying it from there. Once you have these files, it should build and run.
